# Generated by Django 3.0.8 on 2020-07-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_profile_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='Product_Name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Price',
            new_name='Product_Price',
        ),
    ]
