# Generated by Django 3.0.8 on 2020-07-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_company', models.CharField(max_length=100)),
                ('Original_Price', models.FloatField()),
                ('MRP', models.FloatField()),
            ],
        ),
    ]
